version: '3.3'

services:
  lookout:
    image: "srcd/lookout:latest"
    network_mode: "host"
    depends_on:
      - postgres
    environment:
      GITHUB_USER: ${GITHUB_USER:-}
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
    ports:
      - "10301:10301"
    entrypoint: ["/bin/sh"]
    # sleep because container with db is up but the db itself doesn't accept connections yet
    command: ["-c", "sleep 25 && lookoutd migrate && lookoutd serve"]
    volumes:
      #- ./config.yml:/config.yml
      - /lookout/config.yml:/config.yml
      # current direc needs to mapped to /lookout in docker machine (oracle vm)
  dummy:
    image: "srcd/lookout-dummy-analyzer:latest"
    network_mode: "host"
    ports:
      - "9930:9930"
  sonar-check:
    image: "kamimanzoor/lookout-sonarcheck-analyzer:latest"
    network_mode: "host"
    ports:
      - "9929:9929"
    environment:
      SONARCHECK_PORT: 9929
      SONARCHECK_LOG_LEVEL: "debug"
  bblfsh:
    image: "bblfsh/bblfshd:v2.12.1-drivers"
    privileged: true
    ports:
      - "9432:9432"
  postgres:
    image: "postgres:alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lookout
